const styles = {
    head : {
        width: '353px',
        height: '54px',
        paddingTop: 62,
        paddingLeft: 33,
        fontFamily: 'Poppins',
        fontStyle: 'normal',
        fontWeight: '700',
        fontSize: '36px',
        lineHeight: '54px',
        paddingBottom: 14.5,
        color: '#000000',
    },

    inputName : {
        fontFamily: 'Poppins',
        fontSize: '24px',
        fontStyle: 'normal',
        fontWeight: 700,
        lineHeight: '36px',
        letterSpacing: '0em',
        width: '70%',
        margin: '14.5px 74px 14.5px 33px',
        paddingLeft: 21,
        border: 'None',
        borderRadius: 4,
        height: 49,
    },

    inputMessage : {
        fontFamily: 'Poppins',
        fontSize: '24px',
        fontStyle: 'normal',
        fontWeight: 700,
        lineHeight: '36px',
        letterSpacing: '0em',
        width: '70%',
        margin: '14.5px 74px 14.5px 33px',
        paddingLeft: 21,
        border: 'None',
        borderRadius: 4,
        height: 156,
    },
    button: {
        height: '63px',
        fontFamily: 'Poppins',
        fontStyle: 'normal',
        fontWeight: 'bold',
        fontSize: '24px',
        color: '#FFFFFF',
        background: 'rgba(64, 186, 76, 1)',
        margin: '0.5px 74px 14.5px 33px',
        boxBorder: 'None',
        boxShadow: '0px 4px 4px 0px rgba(0, 0, 0, 0.25) inset',
        borderRadius: 12,
        width: '45%',
        '&:hover': {
            backgroundColor: 'rgba(64, 186, 76, 1)',
            boxShadow: 'none',
          },

    },
}

export default styles;